@echo off
REM build_everything.bat -- run every audit, regen, test, and build
REM we have, except `zig build serve`.  Use this before pushing to
REM confirm the tree is in good shape end-to-end.
REM
REM Order: cheap audits -> regens -> tests -> release dist.  Stops
REM on the first failure.
REM
REM Not run from here:
REM   - scripts\build_cheatsheet.py: needs raylib + imgui reference
REM     sources at /tmp/raylib-master/ and /tmp/imgui-master/ (see
REM     src\notes\claude.md for setup).  Run manually when the public
REM     API changes.
REM   - scripts\build_docs.py: docs.html is regenerated by hand
REM     when notes change, not on every build.

setlocal

echo.
echo === [1/8] DAG audit ===
python scripts\check_dag.py
if errorlevel 1 goto :fail

echo.
echo === [2/8] Globals audit ===
python scripts\count_globals.py
if errorlevel 1 goto :fail

echo.
echo === [3/8] Style gate (fmt + lint) ===
zig build lint-check
if errorlevel 1 goto :fail

echo.
echo === [4/8] Regenerate .vscode\launch.json ===
zig build gen-vscode
if errorlevel 1 goto :fail

echo.
echo === [5/8] Host unit tests ===
zig build test --summary all
if errorlevel 1 goto :fail

echo.
echo === [6/8] Windows cross-compile tests ===
zig build test-windows
if errorlevel 1 goto :fail

echo.
echo === [7/8] Wasm smoke tests ===
zig build smoke-test
if errorlevel 1 goto :fail

echo.
echo === [8/8] Release build + refresh prebuilt\ ===
zig build -Drelease=true dist
if errorlevel 1 goto :fail

echo.
echo ============================================
echo   All checks passed.  prebuilt\ is fresh.
echo ============================================
endlocal
exit /b 0

:fail
echo.
echo === FAILED ===
endlocal
exit /b 1
