//! fluid_sort - 20,000-particle Clavet fluid on the GPU, neighbour grid
//!
//! The arc closes: examples/sph_fluid_2d ported the algorithm to a CPU
//! loop because the GL backend had no compute. This is the same paper running
//! where it belongs - eleven kompute kernels (sort_kernels.zig), each
//! translated once to its own WGSL module (spv2wgsl --entry, the multi-kernel
//! path), dispatched through ONE `z.Compute` pipe, rendered zero-copy by
//! `z.FluidDiscs` straight from the compute storage buffer.
//! Positions never visit the CPU.
//!
//! Per substep: gravityMouse -> viscosity -> predict -> [counting sort:
//! clearGrid -> countGrid -> prefixSum -> scatter -> copyback] -> density -> force
//! -> applyAndFinalize, then one instanced draw of N SDF discs coloured by
//! density. The sort reorders pos/vel/prev into cell order so the neighbour
//! passes read contiguous (coalesced) memory - ~3x the per-particle grid.
//!
//! Controls: drag = push, shift+drag (or the attract toggle) = pull; sliders
//! for the paper's four knobs; reset = re-spawn the centre disk.
const std = @import("std");
const Allocator = std.mem.Allocator;
const z = @import("zimr");
const zm = @import("zm");
const float64 = zm.float64;
const float = zm.float;
const Vec2 = zm.Vec2;
const clamp = zm.clamp;
const length = zm.length;
const splat2 = zm.splat2;
const fk = @import("sort_kernels.zig");

const atkinson_mono_ttf = @embedFile("atkinson_mono_ttf");

/// The per-kernel WGSL table, built straight from the kernel manifest
/// (`fk.kernels`) - one `@embedFile` per entry, no hand-kept list to drift out
/// of sync with the kernel file. Each `<name>_wgsl` module is generated by the
/// build's compute pipeline (`spv2wgsl --entry <name>` over the one SPIR-V
/// module). A name in `fk.kernels` with no generated module is a compile error
/// right at the `@embedFile` below - exactly the drift we want caught at build
/// time rather than as a runtime "kernel not registered".
const Pipe = z.Compute(fk);
const kernel_wgsls: [fk.kernels.len]Pipe.KernelWgsl = blk: {
    var arr: [fk.kernels.len]Pipe.KernelWgsl = undefined;
    for (fk.kernels, 0..) |name, i| {
        arr[i] = .{ .name = name, .wgsl = @embedFile(name ++ "_wgsl") };
    }
    break :blk arr;
};

const substeps: u32 = 1;

// THE DEFAULTS, IN ONE PLACE. These must equal the `State` field initialisers below (this
// Zig cannot read struct defaults reflectively, and `State{}` is not constructible because
// `font` has none). They are also `fluid_gpu`'s values - that is what makes the two demos a
// controlled comparison. The DEFAULTS button restores them and the diagnostics panel names
// any knob that has drifted off them.
const def_g_force: f32 = 0.0099; // x 9.8 m/s^2 == fluid_gpu's flat gravity_y of 0.097
const def_rest_density: f32 = 15.39;
const def_visc_beta: f32 = 0.017;
const def_k_far: f32 = 0.009;
const def_k_near: f32 = 0.028;
const def_wall_normal: f32 = 1.0;
const def_wall_tangent: f32 = 0.0;
const def_mouse_force: f32 = 3.0;
const def_phone_gravity: bool = false;
/// Sim-pixel radius of a rendered disc (the reference's RENDER_RADIUS).
const mouse_radius: f32 = 90.0;

const State = struct {
    font: z.Font,
    pipe: z.Compute(fk),
    /// THE SAME KERNELS, RUN AS PLAIN ZIG. kompute compiles one source for two targets, so
    /// this is the only way to ask "is the transpiler lying?" about the PHYSICS kernels.
    /// `sort_smoke` proved the sort and the neighbour walk are bit-correct on the GPU - it
    /// never tested density/force/apply. Toggle this on at a low particle count: if the
    /// fluid pools on the CPU and sprays on the GPU, the fault is in the toolchain, and the
    /// kernel that differs is the one to look at.
    cpu_pipe: z.Compute(fk),
    cpu_sim: bool = false,
    discs: z.FluidDiscs,
    ui_host: z.UiHost,
    /// Persistent spawn/reset scratch (reset re-seeds through the same
    /// upload path; 20k x 8B is cheap to keep).
    scratch: []Vec2,
    // The paper's knobs (uploaded into Params each frame).
    k_far: f32 = def_k_far,
    k_near: f32 = def_k_near,
    // rho 0, the rest/desired density: pressure is k_far*(rho - rho 0). Higher = the
    // fluid wants to pack denser (more cohesive); lower = it expands.
    rest_density: f32 = def_rest_density,
    /// One gain mapping the phone's effective gravity (m/s^2, from the
    /// accelerometer) -> sim acceleration. ~0.01 reproduces "normal" gravity held
    /// upright; this is DOUBLE that, for a punchier default. With phone gravity
    /// off it just scales the straight-down 1g fallback.
    /// MATCHED TO `fluid_gpu`, which applies a flat `gravity_y = 0.097`. Here gravity is a
    /// SCALE on the device's 9.8 m/s^2 vector, so the same downward acceleration needs
    /// 0.097 / 9.8 = 0.0099. (At the old 0.02 this demo pulled twice as hard as the other.)
    g_force: f32 = def_g_force,
    /// On -> gravity comes from the phone's proper-acceleration vector: tilt steers
    /// it, shaking sloshes it, flat = float (zero-g), free-fall = weightless. Off
    /// -> plain straight-down gravity. Needs an https/localhost origin for sensor
    /// data (else it falls back to straight down regardless).
    /// OFF by default, to match `fluid_gpu`, which uses a flat constant gravity.
    ///
    /// With this ON, gravity comes from the ACCELEROMETER - and `getDeviceGravity` maps
    /// only the x,y components into the canvas plane, so a phone held flat (or just tilted
    /// back to read) has almost no in-plane gravity: the fluid is in FREE FALL and expands
    /// to fill the box with no free surface. That is the feature working correctly, but it
    /// made the demo look catastrophically broken next to `fluid_gpu` and sent a long hunt
    /// after a physics bug that did not exist. Tilt-gravity is a great demo - it just
    /// cannot be the DEFAULT when this example's whole purpose is to be a controlled
    /// comparison against a constant-gravity twin.
    phone_gravity: bool = def_phone_gravity,
    /// Wall-contact damping (proportion of velocity removed at the boundary).
    /// normal_damp = into-wall component (1.0 = fully inelastic, the realistic
    /// default); tangent_damp = along-wall friction - kept at 0 now that the
    /// co-location shear (the real cause of the corner jets) is fixed, so the
    /// walls are frictionless and the fix stands on its own. Crank it to compare.
    wall_normal_damp: f32 = def_wall_normal,
    wall_tangent_damp: f32 = def_wall_tangent,
    visc_beta: f32 = def_visc_beta,
    mouse_force_mag: f32 = def_mouse_force,
    attract_toggle: bool = false,
    paused: bool = false,
    /// Batch every substep's dispatches into ONE compute pass / submit
    /// (vs a submit per dispatch). On by default - fewer submits is faster.
    batch_mode: bool = true,
    /// How many particles to DRAW (the sim always runs the full count). Below
    /// the max this shows the first-N in cell order - i.e. the top rows, since
    /// the sort puts the lowest-numbered cells first. Handy for eyeballing the
    /// sort, not a perf knob.
    sim_count_f: f32 = 20000,
    adapter_buf: [192]u8 = undefined,
    adapter_len: usize = 0,
    en_gravity: bool = true,
    en_grid: bool = true,
    en_viscosity: bool = true,
    en_predict: bool = true,
    en_density: bool = true,
    // One-shot: prime the counting sort (build cell_start + sort the spawn
    // layout) before the first substep, so frame 1's viscosity reads a valid
    // grid instead of an uninitialised one.
    sort_primed: bool = false,
    en_force: bool = true,
    en_apply: bool = true,
    /// DIAGNOSTIC PROBE (temporary): particle 0's position and the bbox of all of them,
    /// read back unconditionally. The discs render nothing while the sim reports 8 ms/sub,
    /// so the one question worth answering is whether the POSITIONS are sane. If they are,
    /// the compute is fine and the disc pipeline is at fault; if they are NaN or collapsed,
    /// it is the other way round.
    probe_p0: Vec2 = .{ 0, 0 },
    probe_min: Vec2 = .{ 0, 0 },
    probe_max: Vec2 = .{ 0, 0 },
    probe_nan: u32 = 0,
    /// The effective gravity handed to the kernels this frame (see the diagnostics panel).
    dbg_gravity: Vec2 = .{ 0, 0 },
    probe_pos1: Vec2 = .{ 0, 0 },
    /// RAW first entries of each buffer. Statistics have now sent me down three dead
    /// ends; the actual bytes will not.
    probe_gc: [4]u32 = .{ 0, 0, 0, 0 },
    probe_cs: [4]u32 = .{ 0, 0, 0, 0 },
    probe_den: Vec2 = .{ 0, 0 },
    probe_pos2: Vec2 = .{ 0, 0 },
    /// How many Params fields the SHADER disagrees with the HOST about, and the name of the
    /// first one. Three of twenty have ever been verified; this checks all of them.
    param_bad: u32 = 0,
    param_first: []const u8 = "-",
    param_host: f32 = 0,
    param_gpu: f32 = 0,
    stat_rho: f32 = 0,
    /// Mean rho_near. When `rho` sits BELOW rest density the far-pressure term is
    /// ATTRACTIVE, so the near term is the only thing left that can hold the fluid open -
    /// which makes this the number that decides whether the expansion is even physical.
    stat_rho_near: f32 = 0,
    stat_frozen_pct: f32 = 0,
    // Grid occupancy (from grid_counts readback, diagnostics only): the
    // fullest cell, the mean over non-empty cells, and how many cells exceed
    // the old max_per_cell figure. The counting sort is UNCAPPED, so this no
    // longer means dropped neighbours - it's just a density gauge for tuning.
    stat_cell_max: u32 = 0,
    stat_cell_avg: f32 = 0,
    stat_cells_capped: u32 = 0,
    frame_no: u32 = 0,
    prev_stat_pos: []Vec2,

    // ---- Average-FPS benchmark readout (the baseline-to-beat) ----
    // A STABLE windowed average recomputed every `fps_window_secs` so the
    // displayed value doesn't jitter while you read it; accum/frames build the
    // next window.
    fps_avg: f32 = 0, // published windowed average (the headline number)
    fps_accum_time: f32 = 0, // seconds accumulated in the current window
    fps_accum_frames: u32 = 0,

    // ---- Vsync-independent benchmark ----
    // Run `bench_mult` sim substeps per displayed frame (1..5). Bump it until
    // FPS drops below the refresh cap (frame time past vsync => compute-bound),
    // then ms/substep is the real, vsync-independent throughput figure to
    // compare before/after a change. ms_frame is the EMA of the whole frame.
    bench_mult: u32 = 3,
    ms_frame: f32 = 0,

    // Collapsing-section open state (closed by default - clean main view).
    show_advanced: bool = false,
    show_diag: bool = false,
    // The whole control panel is collapsed by default: just a small menu toggle
    // floats in the corner so the fluid is unobstructed until you want a knob.
    panel_open: bool = false,
};

fn deinit(gpa: Allocator, s: *State) void {
    s.pipe.deinit();
    s.cpu_pipe.deinit();
    s.discs.deinit();
    s.ui_host.deinit();
    gpa.free(s.scratch);
    gpa.free(s.prev_stat_pos);
    z.unloadFont(gpa, s.font);
}

/// Spawn the initial state: a packed disk at domain centre, jittered so the
/// columns don't lock, plus a small deterministic per-particle kick. Uploaded
/// straight into the compute buffers; gravity does the rest. reset() re-runs it.
fn spawnDamBreak(pipe: *z.Compute(fk), scratch: []Vec2) void {
    var prng: std.Random.DefaultPrng = std.Random.DefaultPrng.init(0xf1a1d);
    const rng: std.Random = prng.random();
    var i: u32 = 0;
    while (i < fk.num_particles) : (i += 1) {
        const ang: f32 = rng.float(f32) * 6.2831853;
        const rad: f32 = 220.0 * @sqrt(rng.float(f32));
        scratch[i] = .{
            fk.domain_w * 0.5 + @cos(ang) * rad,
            fk.domain_h * 0.5 + @sin(ang) * rad,
        };
    }
    pipe.upload(.pos, scratch[0..fk.num_particles]);
    @memcpy(fk.g.B.pos[0..fk.num_particles], scratch[0..fk.num_particles]);
    for (scratch[0..fk.num_particles], 0..) |*v, vi| {
        // small deterministic per-particle kick so motion reads on screen
        const a: f32 = float(vi % 628) * 0.01;
        v.* = .{ @cos(a) * 2.0, @sin(a) * 1.0 };
    }
    pipe.upload(.vel, scratch[0..fk.num_particles]);
    @memcpy(fk.g.B.vel[0..fk.num_particles], scratch[0..fk.num_particles]);
    pipe.upload(.delta, scratch[0..fk.num_particles]);
    // Seed density bright so the colour reach-in renders before the first pass.
    for (scratch[0..fk.num_particles]) |*v| {
        v.* = .{ 600.0, 1.0 };
    }
    pipe.upload(.density, scratch[0..fk.num_particles]);
}

fn initState(gpa: Allocator, f: *z.Frame, s: *State) !void {
    const font: z.Font = try z.loadFont(f, gpa, atkinson_mono_ttf, 24);

    var pipe: z.Compute(fk) = try z.Compute(fk).initGpu(
        gpa,
        f.gpu.device,
        f.gpu.queue,
        &kernel_wgsls,
    );

    // Variable-length fields slice to this many elements on readback (the live
    // particle count). Dispatch widths are passed per call to `run(name, n)`;
    // this field is ONLY the readback length, set once here.
    pipe.element_count = fk.num_particles;

    const scratch: []Vec2 = try gpa.alloc(Vec2, fk.num_particles);
    const prev_stat_pos: []Vec2 = try gpa.alloc(Vec2, fk.num_particles);
    @memset(prev_stat_pos, .{ 0, 0 });
    var cpu_pipe: z.Compute(fk) = z.Compute(fk).initCpu();
    cpu_pipe.element_count = fk.num_particles;

    spawnDamBreak(&pipe, scratch);
    spawnDamBreak(&cpu_pipe, scratch);

    const n_bytes: u64 = fk.num_particles * 8;
    const discs: z.FluidDiscs = try z.FluidDiscs.init(
        f.gpu,
        gpa,
        f.gpu.device,
        f.gpu.queue,
        f.gpu.backbuffer_format,
        f.gpu.depth_format orelse .undefined_,
        .{ .handle = pipe.fieldBuffer(.pos).?, .size = n_bytes },
        .{ .handle = pipe.fieldBuffer(.density).?, .size = n_bytes },
        fk.domain_w,
        fk.domain_h,
    );

    s.* = .{
        .font = font,
        .pipe = pipe,
        .cpu_pipe = cpu_pipe,
        .discs = discs,
        .ui_host = z.UiHost.init(gpa, font),
        .scratch = scratch,
        .prev_stat_pos = prev_stat_pos,
    };
}

fn update(f: *z.Frame, s: *State) void {
    // ---- Average-FPS benchmark (the baseline figure we're trying to beat) ----
    // dt is the real frame delta; guard the first frame / pauses where it's 0.
    const dt: f32 = f.time.delta_time;
    if (dt > 0.0) {
        const inst_ms: f32 = dt * 1000.0;
        s.ms_frame = if (s.ms_frame == 0) inst_ms else s.ms_frame * 0.9 + inst_ms * 0.1;
        // Windowed average: accumulate frames, publish every fps_window_secs so
        // the headline number stays stable while you read it.
        s.fps_accum_time += dt;
        s.fps_accum_frames += 1;
        const fps_window_secs: f32 = 0.5;
        if (s.fps_accum_time >= fps_window_secs) {
            s.fps_avg = float(s.fps_accum_frames) / s.fps_accum_time;
            s.fps_accum_time = 0;
            s.fps_accum_frames = 0;
        }
    }

    // ---- Input -> mouse force (logical px -> sim px via the renderer's fit) ----
    const lw: f32 = f.window.widthf();
    const lh: f32 = f.window.heightf();
    const mraw: Vec2 = z.getMousePosition(f.input);
    const mp_arr: [2]f32 = s.discs.simFromLogical(lw, lh, .{ mraw[0], mraw[1] });
    const mp: Vec2 = .{ mp_arr[0], mp_arr[1] };
    const pressing: bool = z.isMouseButtonDown(f.input, .left);
    const attract: bool = s.attract_toggle or
        z.isKeyDown(f.input, .left_shift) or
        z.isKeyDown(f.input, .right_shift);
    const signed_force: f32 = if (!pressing)
        0.0
    else if (attract)
        -s.mouse_force_mag
    else
        s.mouse_force_mag;

    // ---- Gravity: ONE effective-gravity vector from the phone (Einstein) ----
    // getDeviceGravity returns -(proper acceleration) in canvas m/s^2: it already
    // contains gravity AND motion, so tilt, shake, flat-float and free-fall all
    // come from this single vector. g_force scales m/s^2 -> sim units. With phone
    // gravity off it returns plain (0, 9.8), i.e. classic straight-down gravity.
    const eff_g: Vec2 = if (s.phone_gravity) z.getDeviceGravity(f.input) else Vec2{ 0, 9.8 };
    const accel_vec: Vec2 = eff_g * splat2(s.g_force);
    s.dbg_gravity = accel_vec;

    // ---- Substeps: 11 dispatches each, all on-device ----
    // Compute this frame's sim params ONCE, before opening the batch: a batch
    // writes the uniform a single time at beginBatch, so params must be final by
    // then (endBatch asserts they don't change mid-batch). The same values drive
    // the one-time priming sort and every substep below.
    const live_count: u32 = @trunc(clamp(s.sim_count_f, 1, float(fk.num_particles)));

    const sim_params: fk.Params = .{
        // THE LIVE COUNT, not the buffer capacity. This used to be `fk.num_particles`, so
        // the count slider changed only how many discs were DRAWN while the sim always ran
        // all 20000 - and because the counting sort orders particles by cell
        // (`cell = cx + cy*n_cols`), the first N slots are the particles in the LOWEST cell
        // ids, i.e. the TOP ROWS of the domain. Asking for 1000 particles therefore rendered
        // a thin band along the ceiling: a spatial slice, not a subset. In `fluid_gpu` there
        // is no reorder, so the same mistake looked harmless.
        .count = live_count,
        .dt = 1.0,
        .h = fk.interact_radius,
        .r0 = s.rest_density,
        .k_far = s.k_far,
        .k_near = s.k_near,
        .gravity_x = accel_vec[0],
        .gravity_y = accel_vec[1],
        .visc_beta = s.visc_beta,
        .mouse_x = mp[0],
        .mouse_y = mp[1],
        .mouse_force = signed_force,
        .mouse_radius = mouse_radius,
        .dom_w = fk.domain_w,
        .dom_h = fk.domain_h,
        .n_cols = fk.grid_cols,
        .n_rows = fk.grid_rows,
        .wall_normal_damp = s.wall_normal_damp,
        .wall_tangent_damp = s.wall_tangent_damp,
    };
    // ONE pointer decides which backend the whole substep loop runs on. Everything below
    // dispatches through `pipe`, so the CPU and GPU paths cannot drift apart.
    const pipe: *z.Compute(fk) = if (s.cpu_sim) &s.cpu_pipe else &s.pipe;
    pipe.params = sim_params; // non-batch mode reads this per dispatch
    // Echo the uniform back out of the shader every frame, so the panel can prove - not
    // assume - that what the host wrote is what the kernel reads.
    pipe.run("paramEcho", 1);
    if (!s.paused and s.batch_mode and !s.cpu_sim) {
        pipe.beginBatch(sim_params);
    }
    var step: u32 = 0;
    s.frame_no += 1;
    // The benchmark multiplier scales the substep count at runtime so we can
    // push the GPU past the vsync cap and read a real ms/substep number.
    const bench_n: u32 = clamp(s.bench_mult, @as(u32, 1), @as(u32, 5));
    if (!s.paused and !s.sort_primed) {
        // Prime the counting sort once: build cell_start + reorder the spawn
        // layout so the very first substep's viscosity (which runs BEFORE that
        // substep's own rebuild) reads a valid grid, not an uninitialised one.
        pipe.run("clearGrid", fk.grid_cells);
        pipe.run("countGrid", live_count);
        pipe.run("prefixSum", 1);
        pipe.run("scatter", live_count);
        pipe.run("copyback", live_count);
        s.sort_primed = true;
    }
    while (!s.paused and step < substeps * bench_n) : (step += 1) {
        // Clavet ordering: gravity+mouse -> viscosity -> predict, as three
        // dispatches. Viscosity runs on the STALE grid still in the buffer from
        // last frame's build (a damping term tolerates the drift), BEFORE predict
        // and BEFORE the rebuild - so the grid is still built only ONCE per frame
        // (below, on the predicted positions density+force need). Applying
        // viscosity pre-predict (rather than fused into force) is more stable,
        // which lets dt grow.
        if (s.en_gravity) {
            pipe.run("gravityMouse", live_count);
        }
        if (s.en_viscosity) {
            pipe.run("viscosity", live_count);
        }
        if (s.en_predict) {
            pipe.run("predict", live_count);
        }
        if (s.en_grid) {
            // Spatial counting sort: clearGrid (per cell) -> countGrid (per
            // particle) -> prefixSum (ONE invocation) -> scatter -> copyback. After
            // this pos/vel/prev are in CELL ORDER, so each cell's particles occupy
            // the contiguous range [cell_start[c], cell_start[c+1]) and the
            // neighbour passes read coalesced. grid_counts is reused as the
            // per-cell scatter cursor (prefixSum zeroes it after the scan).
            pipe.run("clearGrid", fk.grid_cells);
            pipe.run("countGrid", live_count);
            pipe.run("prefixSum", 1);
            pipe.run("scatter", live_count);
            pipe.run("copyback", live_count);
        }
        if (s.en_density) {
            pipe.run("density", live_count);
        }
        if (s.en_force) {
            pipe.run("force", live_count);
        }
        if (s.en_apply) {
            pipe.run("applyAndFinalize", live_count);
        }
    }
    if (!s.paused and s.batch_mode and !s.cpu_sim) {
        pipe.endBatch();
    }

    // The discs bind GPU buffers, so a CPU-run sim has to be mirrored across before it can
    // be drawn. `readLatest` on `.cpu` is a direct read of the module globals - free.
    if (s.cpu_sim) {
        if (s.cpu_pipe.readLatest(.pos)) |p| {
            s.pipe.upload(.pos, p);
        }
        if (s.cpu_pipe.readLatest(.density)) |d| {
            s.pipe.upload(.density, d);
        }
    }

    // ---- Diagnostics readback (centroid/bbox/rho/frozen) - GATED + THROTTLED.
    // readLatest() copies EVERY GPU buffer to staging + submits + maps (a
    // blocking GPU sync), and the CPU scans 20k elements. Doing all THREE
    // readbacks every frame (for stats only visible in the `diagnostics` panel)
    // pinned the GPU and - critically - added ~3 GPU stalls/frame that inflate
    // ms_frame and distort the ms/sub reading. So only pay for it when the panel
    // is open AND only once every `diag_every` frames; the stat_* fields persist
    // between samples, so the panel still updates (~1x/sec) without taxing every
    // frame. Measure perf with the panel CLOSED for the cleanest number.
    // The probe: unconditional, throttled. One readback every 30 frames is cheap and it
    // answers the only question that matters right now.
    if (s.frame_no % 30 == 0) {
        if (pipe.readLatest(.pos)) |pos_now| {
            var mn: Vec2 = .{ 1e30, 1e30 };
            var mx: Vec2 = .{ -1e30, -1e30 };
            var nan_n: u32 = 0;
            for (pos_now) |p| {
                if (p[0] != p[0] or p[1] != p[1]) {
                    nan_n += 1;
                    continue;
                }
                mn = @min(mn, p);
                mx = @max(mx, p);
            }
            s.probe_p0 = pos_now[0];
            s.probe_pos1 = pos_now[1];
            s.probe_min = mn;
            s.probe_max = mx;
            s.probe_nan = nan_n;
        }
        if (pipe.readLatest(.grid_counts)) |gc| {
            for (0..4) |i| {
                s.probe_gc[i] = gc[i];
            }
        }
        if (pipe.readLatest(.cell_start)) |cs| {
            for (0..4) |i| {
                s.probe_cs[i] = cs[i];
            }
        }
        if (pipe.readLatest(.density)) |d| {
            s.probe_den = d[0];
        }
        if (pipe.readLatest(.scratch)) |sc| {
            s.probe_pos2 = sc[0];

            // WHAT THE SHADER ACTUALLY SEES, field by field, against what the host sent.
            const b: usize = fk.echo_base;
            if (sc.len > b + 9) {
                const Pair = struct { name: []const u8, host: f32, gpu: f32 };
                const checks = [_]Pair{
                    .{ .name = "count", .host = float(sim_params.count), .gpu = sc[b + 0][0] },
                    .{ .name = "dt", .host = sim_params.dt, .gpu = sc[b + 0][1] },
                    .{ .name = "h", .host = sim_params.h, .gpu = sc[b + 1][0] },
                    .{ .name = "r0", .host = sim_params.r0, .gpu = sc[b + 1][1] },
                    .{ .name = "k_far", .host = sim_params.k_far, .gpu = sc[b + 2][0] },
                    .{ .name = "k_near", .host = sim_params.k_near, .gpu = sc[b + 2][1] },
                    .{ .name = "grav_x", .host = sim_params.gravity_x, .gpu = sc[b + 3][0] },
                    .{ .name = "grav_y", .host = sim_params.gravity_y, .gpu = sc[b + 3][1] },
                    .{ .name = "visc", .host = sim_params.visc_beta, .gpu = sc[b + 4][0] },
                    .{ .name = "mouse_x", .host = sim_params.mouse_x, .gpu = sc[b + 4][1] },
                    .{ .name = "mouse_y", .host = sim_params.mouse_y, .gpu = sc[b + 5][0] },
                    .{ .name = "mouse_f", .host = sim_params.mouse_force, .gpu = sc[b + 5][1] },
                    .{ .name = "mouse_r", .host = sim_params.mouse_radius, .gpu = sc[b + 6][0] },
                    .{ .name = "dom_w", .host = sim_params.dom_w, .gpu = sc[b + 6][1] },
                    .{ .name = "dom_h", .host = sim_params.dom_h, .gpu = sc[b + 7][0] },
                    .{ .name = "n_cols", .host = float(sim_params.n_cols), .gpu = sc[b + 7][1] },
                    .{ .name = "n_rows", .host = float(sim_params.n_rows), .gpu = sc[b + 8][0] },
                    .{ .name = "wall_n", .host = sim_params.wall_normal_damp, .gpu = sc[b + 8][1] },
                    .{ .name = "wall_t", .host = sim_params.wall_tangent_damp, .gpu = sc[b + 9][0] },
                };
                var bad: u32 = 0;
                var first: []const u8 = "-";
                var fh: f32 = 0;
                var fg: f32 = 0;
                for (checks) |c2| {
                    if (@abs(c2.host - c2.gpu) > @max(@abs(c2.host) * 0.001, 0.0001)) {
                        if (bad == 0) {
                            first = c2.name;
                            fh = c2.host;
                            fg = c2.gpu;
                        }
                        bad += 1;
                    }
                }
                s.param_bad = bad;
                s.param_first = first;
                s.param_host = fh;
                s.param_gpu = fg;
            }
        }
    }

    const diag_every: u32 = 30;
    if (s.show_diag and s.frame_no % diag_every == 0) {
        if (pipe.readLatest(.pos)) |pos_all| {
            const pos_now: []const Vec2 = pos_all[0..@min(live_count, pos_all.len)];
            var frozen: u32 = 0;
            for (pos_now, 0..) |p, i| {
                const dp: Vec2 = p - s.prev_stat_pos[i];
                if (@abs(dp[0]) + @abs(dp[1]) < 0.01) {
                    frozen += 1;
                }
                s.prev_stat_pos[i] = p;
            }
            s.stat_frozen_pct = 100.0 * float(frozen) / float(live_count);
        }
        if (pipe.readLatest(.density)) |d_all| {
            const d_now: []const Vec2 = d_all[0..@min(live_count, d_all.len)];
            var rs: f64 = 0;
            var rns: f64 = 0;
            for (d_now) |d| {
                rs += d[0];
                rns += d[1];
            }
            s.stat_rho = @floatCast(rs / float64(live_count));
            s.stat_rho_near = @floatCast(rns / float64(live_count));
        }
        if (pipe.readLatest(.grid_counts)) |gc| {
            var cmax: u32 = 0;
            var nonempty: u32 = 0;
            var capped: u32 = 0;
            var total: u64 = 0;
            for (gc) |cnt| {
                if (cnt > cmax) {
                    cmax = cnt;
                }
                if (cnt > 0) {
                    nonempty += 1;
                    total += cnt;
                }
                if (cnt >= fk.max_per_cell) {
                    capped += 1;
                }
            }
            s.stat_cell_max = cmax;
            s.stat_cells_capped = capped;
            const ne_f: f32 = float(nonempty);
            const tot_f: f32 = float(total);
            s.stat_cell_avg = if (nonempty > 0) tot_f / ne_f else 0;
        }
    }

    // ---- Pre-discs marker kept minimal: the FPS/ms readout now lives in the
    // pinned control panel (always visible), so the old top-left headline was
    // both redundant and occluded by the panel - removed. ----

    // ---- Render: clear + N discs (BACKGROUND) + reference geometry + UI ----
    z.clearViewport(f, .{ .r = 1, .g = 3, .b = 8, .a = 255 });

    // Discs FIRST so the 2D overlays + UI compose ON TOP of the fluid. The
    // DrawPoints pass discipline (flushBatch -> disc draw -> renderer.bindForPass)
    // restores the 2D pipeline + bind group, so subsequent 2D draws are valid.
    // Zero-copy: the discs read positions straight from the compute buffer.
    s.discs.draw(f.gl, live_count, lw, lh, .{ .radius_px = 8.0, .density_scale = 1.0 / 24.0 });
    // Reopen a fresh 2D pass after the discs' custom pass so the border and UI
    // compose ON TOP (the disc pass leaves pipeline/pass state the 2D
    // batch can't recover from on the Adreno - the source of the old
    // "discs must be drawn last" workaround).
    z.reopenOverlayPass(f.gl);

    const blind: bool = s.frame_no < 300;
    const so: [2][2]f32 = s.discs.fitScaleOffset(lw, lh);
    const sc: f32 = so[0][0];
    const ox: f32 = so[1][0];
    const oy: f32 = so[1][1];
    // Domain border (2D layer, logical coords): where FluidDiscs SHOULD map.
    f.gl.rect(
        .{ .x = ox, .y = oy, .width = fk.domain_w * sc, .height = fk.domain_h * sc },
        .{ .color = .{ .r = 90, .g = 200, .b = 90, .a = 255 }, .outline = 2.0 },
    );
    if (blind) {
        const badge_pos: Vec2 = .{ ox + fk.domain_w * sc - 30.0 * sc, oy + 18.0 * sc };
        f.gl.rect(
            .{ .x = badge_pos[0], .y = badge_pos[1], .width = 22.0 * sc, .height = 22.0 * sc },
            .{ .color = .{ .r = 240, .g = 240, .b = 240, .a = 255 } },
        );
    }

    // ---- Controls ----
    const u: z.ui_real.Ui = s.ui_host.begin(f);
    // Phone strategy: a SMALL always-visible bar (fps + a menu toggle) floats at
    // the top-left so the fluid is unobstructed. Tapping menu opens the full
    // control panel; tapping x collapses it. Font is sized to the logical
    // width so nothing clips on a narrow canvas. lw/lh = logical CSS px.
    const ui_w: f32 = lw * 0.5;
    // 30% smaller than the previous sizing: cap 34->24, and the divisor tracks
    // the (now half-width) panel so text still fits.
    const fsz: f32 = clamp(ui_w / 16.0, 12.0, 24.0);
    u.style().font_size = fsz;
    u.style().frame_padding = .{ fsz * 0.35, fsz * 0.3 };
    u.style().item_spacing = .{ fsz * 0.4, fsz * 0.4 };
    u.style().window_padding = .{ fsz * 0.5, fsz * 0.5 };
    u.style().title_bar_height = fsz * 1.6;

    // The compact toggle bar - always visible, minimal footprint.
    u.setNextWindowPos(.{ 0, 0 }, .{});
    u.setNextWindowSize(.{ ui_w, fsz * 2.6 }, .{});
    if (u.window("hud", .{ .flags = .{ .no_move = true, .no_resize = true, .no_title_bar = true } })) |w| {
        defer w.close();
        const sub_n: f32 = float(clamp(s.bench_mult, @as(u32, 1), @as(u32, 5)));
        const toggle_label: []const u8 = if (s.panel_open) "X" else "=";
        if (u.button(toggle_label, .{ .size = .{ fsz * 1.8, fsz * 1.8 } })) {
            s.panel_open = !s.panel_open;
        }
        u.sameLine(.{});
        u.text("{d:.0} fps  {d:.1} ms/sub  [{s}]", .{
            s.fps_avg,
            s.ms_frame / sub_n,
            "sorted",
        });
    }

    // The full control panel - only when opened.
    if (s.panel_open) {
        u.setNextWindowPos(.{ 0, fsz * 2.8 }, .{});
        u.setNextWindowSize(.{ ui_w, lh - fsz * 2.8 }, .{});
        if (u.window("fluid", .{ .flags = .{ .no_move = true, .no_resize = true } })) |w| {
            defer w.close();

            // ---- Benchmark stepper (-  N  +), 1..5. Big square buttons: no
            // keyboard, big targets, whole range in <=4 taps. ----
            u.text("substeps:", .{});
            const bw: f32 = fsz * 2.0;
            if (u.button("-", .{ .size = .{ bw, bw } })) {
                if (s.bench_mult > 1) {
                    s.bench_mult -= 1;
                }
            }
            u.sameLine(.{});
            u.text(" {d} ", .{s.bench_mult});
            u.sameLine(.{});
            if (u.button("+", .{ .size = .{ bw, bw } })) {
                if (s.bench_mult < 5) {
                    s.bench_mult += 1;
                }
            }

            _ = u.checkbox("pause", &s.paused);
            u.sameLine(.{});
            if (u.button("reset", .{ .size = .{ 0, fsz * 2.0 } })) {
                spawnDamBreak(&s.pipe, s.scratch);
                spawnDamBreak(&s.cpu_pipe, s.scratch);
            }
            u.sameLine(.{});
            // Restore EVERY physics knob to its default. On a phone the panel scrolls
            // under the same finger that drags a slider, so it is easy to knock `rest
            // density` or `wall normal` off without noticing - and this fluid is very
            // sensitive to them (pressure is k*(rho - rho0), so a rest density set BELOW
            // the actual density flips attraction into repulsion and the fluid expands to
            // fill the box). One button to get back to a known state.
            if (u.button("DEFAULTS", .{ .size = .{ 0, fsz * 2.0 } })) {
                s.g_force = def_g_force;
                s.rest_density = def_rest_density;
                s.visc_beta = def_visc_beta;
                s.k_far = def_k_far;
                s.k_near = def_k_near;
                s.wall_normal_damp = def_wall_normal;
                s.wall_tangent_damp = def_wall_tangent;
                s.mouse_force_mag = def_mouse_force;
                s.phone_gravity = def_phone_gravity;
                s.sim_count_f = float(fk.num_particles);
                spawnDamBreak(&s.pipe, s.scratch);
                spawnDamBreak(&s.cpu_pipe, s.scratch);
            }

            // COUNT PRESETS. A slider spanning 1..20000 cannot be dragged to 200 on a phone,
            // and a small count is the fastest way to SEE what the fluid is doing rather
            // than infer it from aggregate statistics.
            u.text("count:", .{});
            inline for (.{ 100, 1000, 5000, 20000 }) |n| {
                if (u.button(std.fmt.comptimePrint("{d}", .{n}), .{ .size = .{ fsz * 4.0, fsz * 2.0 } })) {
                    s.sim_count_f = @floatFromInt(n);
                    spawnDamBreak(&s.pipe, s.scratch);
                    spawnDamBreak(&s.cpu_pipe, s.scratch);
                }
                u.sameLine(.{});
            }
            u.text("", .{});

            // FREE FALL: one tap to remove EVERY pressure term (density, force, viscosity),
            // leaving gravity -> predict -> grid -> apply. With nothing holding them apart
            // the particles MUST pile on the floor like sand. If they do, gravity,
            // integration and the walls are sound and the fault is in the pressure stage.
            // If they hang in the air, gravity never reaches the kernels and every pressure
            // number I have been reading is beside the point. One tap, and it splits the
            // remaining search space in half.
            // THE SAME KERNELS AS PLAIN ZIG. `sort_smoke` proved the sort and the neighbour
            // walk are bit-correct on the GPU, but it never tested density/force/apply. If
            // the fluid POOLS here and SPRAYS on the GPU, the toolchain miscompiles one of
            // those three - and that is a completely different bug from a physics mistake.
            // Use a low count: the CPU runs 20k particles far too slowly to watch.
            _ = u.checkbox("CPU KERNELS (same source)", &s.cpu_sim);

            const free_fall: bool = !s.en_density and !s.en_force and !s.en_viscosity;
            if (u.button(if (free_fall) "FREE FALL: ON" else "free fall test", .{
                .size = .{ 0, fsz * 2.0 },
            })) {
                const on: bool = !free_fall;
                s.en_density = !on;
                s.en_force = !on;
                s.en_viscosity = !on;
                spawnDamBreak(&s.pipe, s.scratch);
                spawnDamBreak(&s.cpu_pipe, s.scratch);
            }

            _ = u.slider("count", &s.sim_count_f, .{ .min = 1, .max = 20000, .fmt = "{d:.0}" });
            _ = u.slider("g-force", &s.g_force, .{ .min = 0, .max = 0.06, .fmt = "{d:.3}" });
            _ = u.checkbox("phone gravity", &s.phone_gravity);
            _ = u.slider("wall normal", &s.wall_normal_damp, .{ .min = 0, .max = 1, .fmt = "{d:.2}" });
            _ = u.slider("wall friction", &s.wall_tangent_damp, .{ .min = 0, .max = 1, .fmt = "{d:.2}" });
            {
                // Readout: g = effective gravity vector (canvas m/s^2, pre-gain),
                // |g| = its magnitude (~9.8 upright, ->0 flat/free-fall). If tilt
                // pulls the "wrong way", this is what to flip in getDeviceGravity.
                const g: Vec2 = z.getDeviceGravity(f.input);
                const gmag: f32 = length(g);
                u.text("g=({d:.1},{d:.1}) |g|={d:.1} ang={d:.0}", .{
                    g[0],
                    g[1],
                    gmag,
                    f.input.motion.screen_angle,
                });
                // Diagnostic for the frame-duplication report: the logical (CSS)
                // size the engine renders into vs the backing (device-px) target.
                // If win is portrait-shaped while the display is landscape, or px
                // isn't a clean multiple of win, the surface is mis-sized.
                u.text("win=({d:.0}x{d:.0}) px=({d}x{d})", .{
                    f.window.widthf(),
                    f.window.heightf(),
                    f.gl.render_w,
                    f.gl.render_h,
                });
            }
            _ = u.slider("viscosity", &s.visc_beta, .{ .min = 0, .max = 0.5 });
            _ = u.slider("rest density", &s.rest_density, .{ .min = 0, .max = 30, .fmt = "{d:.1}" });
            _ = u.checkbox("attract", &s.attract_toggle);

            // ---- Advanced (collapsed) ----
            if (u.collapsingHeader("advanced", &s.show_advanced)) {
                _ = u.slider("k far", &s.k_far, .{ .min = 0, .max = 0.02, .fmt = "{d:.4}" });
                _ = u.slider("k near", &s.k_near, .{ .min = 0, .max = 0.06, .fmt = "{d:.4}" });
                _ = u.checkbox("batch", &s.batch_mode);
            }

            // ---- Diagnostics (collapsed; readback only runs while open) ----
            if (u.collapsingHeader("diagnostics", &s.show_diag)) {
                // WHICH KNOBS ARE OFF DEFAULT. On a phone the panel scrolls under the same
                // finger that drags a slider, so knobs get knocked without anyone noticing -
                // and this fluid is very sensitive to k_far/k_near/rest_density. Three
                // separate debugging sessions were spent chasing "bugs" that were really a
                // nudged slider. Now every screenshot says so.
                var off: [7][]const u8 = undefined;
                var n_off: usize = 0;
                if (s.k_far != def_k_far) {
                    off[n_off] = "k_far";
                    n_off += 1;
                }
                if (s.k_near != def_k_near) {
                    off[n_off] = "k_near";
                    n_off += 1;
                }
                if (s.rest_density != def_rest_density) {
                    off[n_off] = "rest";
                    n_off += 1;
                }
                if (s.visc_beta != def_visc_beta) {
                    off[n_off] = "visc";
                    n_off += 1;
                }
                if (s.g_force != def_g_force) {
                    off[n_off] = "g";
                    n_off += 1;
                }
                if (s.wall_normal_damp != def_wall_normal) {
                    off[n_off] = "wall_n";
                    n_off += 1;
                }
                if (s.phone_gravity != def_phone_gravity) {
                    off[n_off] = "phone_g";
                    n_off += 1;
                }
                if (n_off == 0) {
                    u.text("knobs: DEFAULT", .{});
                } else {
                    switch (n_off) {
                        1 => u.text("knobs OFF-DEFAULT: {s}", .{off[0]}),
                        2 => u.text("knobs OFF-DEFAULT: {s} {s}", .{ off[0], off[1] }),
                        3 => u.text("knobs OFF-DEFAULT: {s} {s} {s}", .{ off[0], off[1], off[2] }),
                        else => u.text("knobs OFF-DEFAULT: {s} {s} {s} +{d}", .{ off[0], off[1], off[2], n_off - 3 }),
                    }
                }
                if (s.param_bad == 0) {
                    u.text("PARAMS: all 19 reach the shader", .{});
                } else {
                    u.text("PARAMS WRONG: {d}! {s} host={d:.4} gpu={d:.4}", .{
                        s.param_bad, s.param_first, s.param_host, s.param_gpu,
                    });
                }
                u.text("rho {d:.1}  rho_near {d:.1}  frozen {d:.0}%", .{
                    s.stat_rho, s.stat_rho_near, s.stat_frozen_pct,
                });
                // The two pressure terms as the kernel actually computes them, at the MEAN
                // density. far = k_far*(rho - r0) is negative below rest (attraction);
                // near = k_near*rho_near is ALWAYS positive (repulsion). If |near| > |far|
                // the fluid cannot settle no matter what else is right.
                u.text("far {d:.4}  near {d:.4}", .{
                    s.k_far * (s.stat_rho - s.rest_density),
                    s.k_near * s.stat_rho_near,
                });
                // The EFFECTIVE gravity actually fed to the kernels. With `phone gravity`
                // on this is the accelerometer's in-plane component, which goes to ~0 when
                // the phone lies flat - and a zero here is the whole explanation for a
                // fluid that fills the box instead of pooling.
                u.text("g ({d:.3}, {d:.3})", .{ s.dbg_gravity[0], s.dbg_gravity[1] });
                u.text("p0 ({d:.1},{d:.1})", .{ s.probe_p0[0], s.probe_p0[1] });
                u.text("x [{d:.0} .. {d:.0}]", .{ s.probe_min[0], s.probe_max[0] });
                u.text("y [{d:.0} .. {d:.0}]", .{ s.probe_min[1], s.probe_max[1] });
                u.text("nan {d}  domain {d:.0}x{d:.0}", .{ s.probe_nan, fk.domain_w, fk.domain_h });
                // THE DECISIVE PROBE: the raw GPU buffer handles behind each field. If any
                // two of these are EQUAL, the per-field buffers alias - and that single
                // fault explains every symptom at once: positions reading back as density
                // values (5..11), grid_counts reading back as a prefix-sum ramp, and the
                // discs drawing density-as-position into the corner.
                // The handle a missing field reports as; 0 is the invalid-buffer value.
                const no_buf: z.wgpu.BufferHandle = @fromBackingInt(@intCast(0));
                u.text("h pos={d} den={d}", .{
                    @backingInt(s.pipe.fieldBuffer(.pos) orelse no_buf),
                    @backingInt(s.pipe.fieldBuffer(.density) orelse no_buf),
                });
                u.text("h gc={d} cs={d}", .{
                    @backingInt(s.pipe.fieldBuffer(.grid_counts) orelse no_buf),
                    @backingInt(s.pipe.fieldBuffer(.cell_start) orelse no_buf),
                });
                u.text("gc  {d} {d} {d} {d}", .{ s.probe_gc[0], s.probe_gc[1], s.probe_gc[2], s.probe_gc[3] });
                // The one link never measured: what the HOST holds at write time. Every
                // other layer has now been verified to agree on n_cols living at byte 60
                // (Zig extern, SPIR-V OpMemberDecorate Offset, WGSL). So either the host
                // value is not what the literal says, or the write drops it.
                u.text("HOST: n_cols={d} n_rows={d}", .{ s.pipe.params.n_cols, s.pipe.params.n_rows });
                u.text("cs {d} {d} {d} {d}", .{ s.probe_cs[0], s.probe_cs[1], s.probe_cs[2], s.probe_cs[3] });
                u.text("den ({d:.2},{d:.2})  pos2 ({d:.1},{d:.1})", .{
                    s.probe_den[0], s.probe_den[1], s.probe_pos2[0], s.probe_pos2[1],
                });
                u.text("p1 ({d:.1},{d:.1})  ncols {d} nrows {d}", .{
                    s.probe_pos1[0], s.probe_pos1[1], fk.grid_cols, fk.grid_rows,
                });
                u.text("buffers {d} (WebGPU max 8)  cells {d}", .{
                    @typeInfo(fk.Buffers).@"struct".field_names.len,
                    fk.grid_cells,
                });
                u.text("cellmax {d} avg {d:.1} cap {d}", .{ s.stat_cell_max, s.stat_cell_avg, s.stat_cells_capped });
                _ = u.checkbox("gravity", &s.en_gravity);
                _ = u.checkbox("viscosity (pre-predict)", &s.en_viscosity);
                _ = u.checkbox("grid", &s.en_grid);
                _ = u.checkbox("predict", &s.en_predict);
                _ = u.checkbox("density", &s.en_density);
                _ = u.checkbox("force", &s.en_force);
                _ = u.checkbox("apply", &s.en_apply);
            }
        }
    }
    s.ui_host.render(f);
}

pub const app: z.AppSpec(State) = .{
    // Transient GPU compute demo: pipeline/shader setup handles aren't retained
    // in State, so a leak-tight deinit isn't practical - opt out of the gate.
    .memory = .managed,
    .config = .{
        .window = .{
            .title = "zimr - WebGPU - 20k GPU fluid (sorted)",
            .width = 900,
            .height = 600,
            .scale_mode = .responsive,
        },
    },
    .init = initState,
    .deinit = deinit,
    .update = update,
    // .memory left default (arena): a pre-existing queue-timeline clobber
    // (kompute_params, frame 0) - part of the live t1178 inter-submit
    // coherency hunt, not the init-shape change - trips the smoke's frame
    // scan regardless of memory mode, so the managed leak-gate is deferred.
};
