//! examples/shader_uniforms_fs.zig — mouse-driven spiral fragment
//! shader with iface co-located in this file (Inputs / Outputs /
//! Ubo at the top, body below).
//!
//! Companion to `examples/shader_uniforms.zig`.  Uses `frag_tex_coord
//! * u.resolution` for the pixel-space position (unit-agnostic — the
//! shader's math cancels the unit out via the division by
//! `u.resolution.y`, so the host can stay in logical px without any
//! DPR conversion).  HSV→RGB block matches mandelbrot's; the
//! interesting bit is the angle/radius polar mapping driving the hue.
//!
//! Migrated 2026-05-27 from the legacy hand-written-externs pattern
//! to typed inline-iface as part of the build.zig explicit-shader-
//! table refactor.  Same shader logic, same GLSL output; the
//! external decls are now generated by codegen instead of hand-
//! maintained in this file.

const zm = @import("zm");
const Vec = zm.Vec;
const Vec2 = zm.Vec2;
const Vec3 = zm.Vec3;
const atan2 = zm.atan2;
const clamp = zm.clamp;
const clamp01 = zm.clamp01;
const fract = zm.fract;
const length = zm.length;
const tau = zm.tau;
const vec2 = zm.vec2;
const vec3 = zm.vec3;
const vec4 = zm.vec4;
const shader_io = @import("shader_uniforms_fs_io.zig");
const shader_externs = @import("shader_uniforms_fs_externs");

pub const Io = shader_externs.IoT(shader_io.Ubo);
pub const Out = shader_externs.Out;

// HSV → RGB.  Standard Iñigo Quilez form.  Returns a Vec3 with each
// component in [0, 1].  `pub fn` (not `pub inline fn`) — Zig's SPIR-V
// backend's inline pass breaks structured-control-flow markers;
// spirv-opt inlines properly post-codegen.
fn hsv2rgb(c: Vec3) Vec3 {
    const k: Vec = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);
    const cxyz: Vec3 = vec3(c[0], c[0], c[0]);
    const kxyz: Vec3 = vec3(k[0], k[1], k[2]);
    const sum: Vec3 = cxyz + kxyz;
    const f: Vec3 = vec3(fract(sum[0]), fract(sum[1]), fract(sum[2]));
    const six: Vec3 = vec3(6.0, 6.0, 6.0);
    const t: Vec3 = f * six - vec3(3.0, 3.0, 3.0);
    const p: Vec3 = vec3(@abs(t[0]), @abs(t[1]), @abs(t[2]));
    const p_clamped: Vec3 = vec3(
        clamp01(p[0] - 1.0),
        clamp01(p[1] - 1.0),
        clamp01(p[2] - 1.0),
    );
    const kxxx: Vec3 = vec3(k[0], k[0], k[0]);
    const sat: Vec3 = vec3(c[1], c[1], c[1]);
    const mixed: Vec3 = kxxx + (p_clamped - kxxx) * sat;
    const val: Vec3 = vec3(c[2], c[2], c[2]);
    return mixed * val;
}

pub fn shaderMain(io_in: Io) Out {
    var out: Out = undefined;

    // Pixel-space position derived from frag_tex_coord (already 0..1
    // across the rect) times resolution.  Both mouse and resolution
    // are in the same units, so the division by resolution.y in
    // `to_mouse` cancels the unit out — this shader is DPR-agnostic.
    const frag: Vec2 = io_in.frag_tex_coord * io_in.u.resolution;
    const inv_h: Vec2 = vec2(1.0 / io_in.u.resolution[1], 1.0 / io_in.u.resolution[1]);
    const to_mouse: Vec2 = (frag - io_in.u.mouse) * inv_h;
    const r: f32 = length(to_mouse);
    const angle: f32 = atan2(to_mouse[1], to_mouse[0]);

    const hue_raw: f32 = (angle / tau + 0.5) + @sin(r * 12.0 - io_in.u.time * 1.5) * 0.15 + io_in.u.time * 0.05;
    const hue: f32 = fract(hue_raw);

    const sat: f32 = 0.8;
    const val: f32 = clamp(1.0 - r * 0.6, 0.2, 1.0);

    const rgb: Vec3 = hsv2rgb(vec3(hue, sat, val));
    out.out_color = vec4(rgb[0], rgb[1], rgb[2], 1.0);
    return out;
}

comptime {
    _ = shader_externs.installSpirvEntry(shaderMain);
}
