//! examples/sw_mandelbrot.zig — Software-rendered Mandelbrot through
//! zimr's turn-3 typed-pipeline architecture.
//!
//! This is the headline demo of the SW dispatch foundation:
//!
//!   - Shader is a plain Zig struct with `pub fn shaderMain(io: Io) Out`
//!   - Pipeline type carries the VS+FS shader types as comptime parameters
//!   - Dispatch goes through a per-pipeline-TYPE comptime vtable
//!   - One indirect call per draw — zero virtual dispatch per pixel
//!   - `rasterizeTriangles` inlines `Fs.shaderMain` into the rasterizer's
//!     inner pixel loop, giving the same code quality as a hand-coded
//!     SW renderer
//!
//! Run:
//!
//!   zig build sw-mandelbrot
//!   convert mandelbrot.ppm mandelbrot.png  # if you have imagemagick
//!
//! The same Zig source IS the WebGPU shader (turn 2/3 plan).  Today the
//! native side is wired through `raster_shader.rasterizeTriangles`; the
//! GPU side compiles to SPIR-V→WGSL and runs in the browser.

const std = @import("std");
const Allocator = std.mem.Allocator;
// GL-retirement P2: migrated off the GL `zimr` umbrella onto the native
// SW bundle (raster + raster_shader + codecs + math + the typed-pipeline pieces).
const sw = @import("sw_runtime");
const zm = @import("zm");
const Vec = zm.Vec;
const Vec2 = zm.Vec2;
const float64 = zm.float64;
const float = zm.float;
const maxInt = zm.maxInt;

const raster = sw.raster;
const raster_shader = sw.raster_shader;
const wgpu = sw.wgpu;
const shader_runtime = sw.shader_runtime_wgpu;
const gpu_iface = sw.gpu_iface;

// ============================================================================
// SECTION 1 — the shader pair
// ============================================================================

/// Vertex shader.  Trivial passthrough — takes NDC position and UV from
/// vertex attributes, emits position to gl_Position and UV as a varying
/// to the fragment stage.  Same shape the WebGPU SPIR-V build sees;
/// `raster_shader.dispatchVertexShader` calls this per vertex on the
/// native side.
const FullscreenVs = struct {
    pub const Io = struct {
        attr_position: Vec2,
        attr_uv: Vec2,
    };
    pub const Out = struct {
        position: Vec,
        frag_uv: Vec2,
    };
    pub fn shaderMain(io: Io) Out {
        return .{
            .position = .{ io.attr_position[0], io.attr_position[1], 0, 1 },
            .frag_uv = io.attr_uv,
        };
    }
};

/// Fragment shader.  Receives interpolated UV in [0, 1]².  Maps UV to
/// the complex plane window and runs the Mandelbrot iteration; encodes
/// the iteration count as a color via a smooth palette.
///
/// `connect` between VS and FS is auto-generated by `autoConnect` —
/// `frag_uv` is in both VsOut and FsIo, so it copies field-by-field
/// at comptime.  No per-pair adapter to write.
const MandelbrotFs = struct {
    pub const Io = struct {
        frag_uv: Vec2,
    };
    pub const Out = struct {
        out_color: Vec,
    };

    /// The complex-plane window: roughly the classic Mandelbrot view
    /// centered on the body, zoomed to show the main features.
    const RE_CENTER: f32 = -0.7;
    const IM_CENTER: f32 = 0.0;
    const VIEW_W: f32 = 3.0;
    const VIEW_H: f32 = 2.4;
    const MAX_ITER: u32 = 256;

    pub fn shaderMain(io: Io) Out {
        // UV [0, 1]² → complex plane (cx, cy)
        const u: f32 = io.frag_uv[0];
        const v: f32 = io.frag_uv[1];
        const cx: f32 = RE_CENTER + (u - 0.5) * VIEW_W;
        const cy: f32 = IM_CENTER + (v - 0.5) * VIEW_H;

        // Iterate z_(n+1) = z_n² + c.  Standard Mandelbrot kernel.
        // Bail-out radius of 4 is the classic; using a larger radius
        // (256) lets the smooth-coloring formula below converge to
        // a cleaner continuous gradient (fewer banding artifacts).
        const BAIL_R2: f32 = 256.0;
        var zx: f32 = 0;
        var zy: f32 = 0;
        var iter: u32 = 0;
        var zx2: f32 = 0;
        var zy2: f32 = 0;
        while (iter < MAX_ITER) : (iter += 1) {
            zx2 = zx * zx;
            zy2 = zy * zy;
            if (zx2 + zy2 > BAIL_R2) break;
            const zxy_new = 2 * zx * zy + cy;
            const zx_new = zx2 - zy2 + cx;
            zx = zx_new;
            zy = zxy_new;
        }

        // Interior → black.
        if (iter == MAX_ITER) {
            return .{ .out_color = .{ 0, 0, 0, 1 } };
        }

        // Smooth coloring: nu = iter + 1 - log2(log(|z|)).  The
        // log-log trick removes the discrete step at the bail-out
        // boundary; the continuous escape value gives banding-free
        // gradients.  Reference: Linas Vepstas, "Renormalizing the
        // Mandelbrot escape."
        const mag2: f32 = zx2 + zy2;
        const log_mag: f32 = 0.5 * @log(mag2);
        const nu: f32 = float(iter) + 1.0 -
            @log2(log_mag);
        const t: f32 = nu * 0.03; // palette period — tuned by eye

        // Palette: a five-stop gradient sampled from the classic
        // "Ultra Fractal" Mandelbrot scheme.  Smooth interpolation
        // via cosines in three phase-shifted channels gives a
        // rich navy-→-cream-→-orange-→-purple-→-cyan cycle.
        const PI2: f32 = 6.28318530718;
        const r: f32 = 0.5 + 0.5 * @cos(PI2 * (t * 1.0 + 0.00));
        const g: f32 = 0.5 + 0.5 * @cos(PI2 * (t * 1.0 + 0.10));
        const b: f32 = 0.5 + 0.5 * @cos(PI2 * (t * 1.0 + 0.20));
        return .{ .out_color = .{ r, g, b, 1 } };
    }
};

// ============================================================================
// SECTION 2 — the pipeline (turn-3 architecture)
// ============================================================================

/// Custom pipeline struct shaped for `gpu_iface.setPipeline` to accept.
/// Has the four required decls: `Vs`, `Fs`, `gpu_handle`, `sw_dispatch`.
/// `sw_dispatch` is a per-TYPE comptime const — no allocation, no
/// per-instance setup.  Calling `setPipeline(&ps, pipeline)` reads
/// `&@TypeOf(pipeline).sw_dispatch` and stores it on `PassState`.
const MandelbrotPipeline = struct {
    gpu_handle: wgpu.RenderPipelineHandle = .invalid,
    pub const Vs = FullscreenVs;
    pub const Fs = MandelbrotFs;
    pub const sw_dispatch: ?*const shader_runtime.SwPipelineDispatch =
        &Dispatch.vtable;

    const Dispatch = struct {
        const vtable = shader_runtime.SwPipelineDispatch{
            .flush_batch = &flushBatch,
        };

        /// The closure that flushes a draw call through the SW renderer.
        /// Comptime-specialized over `FullscreenVs` and `MandelbrotFs`
        /// because the closure captures these types statically.  Inside,
        /// `raster_shader.rasterizeTriangles` is called with the comptime
        /// shader types, which lets it inline `MandelbrotFs.shaderMain`
        /// into the rasterizer's inner pixel loop.
        fn flushBatch(ctx_opaque: *anyopaque, ps_opaque: *anyopaque) void {
            const ctx: *raster.Context = @ptrCast(@alignCast(ctx_opaque));
            _ = ps_opaque;

            // Fullscreen quad in NDC, two triangles, CCW winding so
            // back-face culling keeps them.
            const vs_outs = [_]FullscreenVs.Out{
                // Triangle 1: bottom-left, top-left, bottom-right
                .{ .position = .{ -1, -1, 0, 1 }, .frag_uv = .{ 0, 0 } },
                .{ .position = .{ -1, 1, 0, 1 }, .frag_uv = .{ 0, 1 } },
                .{ .position = .{ 1, -1, 0, 1 }, .frag_uv = .{ 1, 0 } },
                // Triangle 2: top-left, top-right, bottom-right
                .{ .position = .{ -1, 1, 0, 1 }, .frag_uv = .{ 0, 1 } },
                .{ .position = .{ 1, 1, 0, 1 }, .frag_uv = .{ 1, 1 } },
                .{ .position = .{ 1, -1, 0, 1 }, .frag_uv = .{ 1, 0 } },
            };
            const indices = [_]u32{ 0, 1, 2, 3, 4, 5 };

            // autoConnect generates the VsOut → FsIo mapping by walking
            // matching field names at comptime — `frag_uv` is in both,
            // so it's copied; `position` is excluded (used by the
            // rasterizer for screen-space, not as a varying).
            const connect = comptime shader_runtime.autoConnect(
                FullscreenVs.Out,
                MandelbrotFs.Io,
            );

            raster_shader.rasterizeTriangles(
                FullscreenVs,
                MandelbrotFs,
                ctx,
                &vs_outs,
                &indices,
                .{ .frag_uv = .{ 0, 0 } }, // base FS Io — overwritten by interpolation
                connect,
                // Pre-existing geometry uses the old screen-space CCW
                // = clip-space CW convention; preserve via `.cw`.
                .{ .front_face = .cw },
            );
        }
    };
};

// ============================================================================
// SECTION 3 — PPM writer
// ============================================================================

/// Write the raster context's color buffer as a PNG file using zimr's
/// built-in encoder.  raster stores RGBA8 — codecs.png.encode handles
/// that layout directly.  File I/O takes the application's `io` (the
/// `std.Io` created in `main`), threaded like the allocator.
fn writePng(
    gpa: Allocator,
    io: std.Io,
    path: []const u8,
    bytes: []const u8,
    width: u32,
    height: u32,
) !void {
    const png_bytes: []u8 = try sw.codecs.png.encode(gpa, bytes, width, height);
    defer gpa.free(png_bytes);
    var f: std.Io.File = try std.Io.Dir.cwd().createFile(io, path, .{});
    defer f.close(io);
    try f.writeStreamingAll(io, png_bytes);
}

// ============================================================================
// SECTION 4 — main
// ============================================================================

/// Monotonic clock in nanoseconds.  Zig 0.16's `std.time` is just
/// constants; for the actual clock we go through posix.  Linux/macOS
/// hosts (where this demo runs) all have clock_gettime.
fn monotonicNs() i128 {
    var ts: std.posix.timespec = undefined;
    _ = std.posix.system.clock_gettime(.MONOTONIC, &ts);
    return @as(i128, ts.sec) * 1_000_000_000 + @as(i128, ts.nsec);
}

pub fn main() !void {
    var gpa_impl: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa_impl.deinit();
    const gpa: Allocator = gpa_impl.allocator();

    // The application picks the I/O implementation in main and threads it to
    // anything that reads/writes (currently std.Io.Threaded is the only one).
    var io_threaded: std.Io.Threaded = .init(gpa, .{});
    defer io_threaded.deinit();
    const io: std.Io = io_threaded.io();

    const WIDTH: u32 = 1280;
    const HEIGHT: u32 = 720;

    std.debug.print(
        "zimr SW renderer demo — Mandelbrot at {d}×{d}\n" ++
            "(through the turn-3 typed-pipeline architecture)\n\n",
        .{ WIDTH, HEIGHT },
    );

    // 1. Set up the raster context — the SW framebuffer.
    var ctx: raster.Context = try .init(gpa, WIDTH, HEIGHT);
    defer ctx.deinit(gpa);
    ctx.clearColor(.{ .r = 0, .g = 0, .b = 0, .a = 255 });
    ctx.clear(.{ .color = true });

    // 2. Construct the typed pipeline.  `gpu_handle` is `.invalid`
    // (no GPU in this demo); `sw_dispatch` (comptime const on the
    // type) carries the vtable.
    const pipeline: MandelbrotPipeline = .{};

    // 3. Set up PassState — this is what the trait threads through.
    // `pass = .invalid` because we're not using a real wgpu pass.
    var ps: gpu_iface.PassState = .{ .pass = .invalid };

    // 4. setPipeline records the SW vtable on PassState.
    // The trait call is the same shape as the wgpu path uses.
    gpu_iface.SwBackend.setPipeline(&ps, pipeline);
    if (ps.sw_dispatch == null) {
        std.debug.print("error: pipeline has no SW dispatcher\n", .{});
        return error.NoSwDispatch;
    }

    // 5. Time the render across multiple iterations.  Single-shot
    // measurements are noisy; we report min over a small batch so
    // first-call paging/cache effects don't dominate.
    const ITERS: u32 = 5;
    var min_ns: i128 = maxInt(i128);
    var i: u32 = 0;
    while (i < ITERS) : (i += 1) {
        ctx.clear(.{ .color = true });
        const start_ns = monotonicNs();
        ps.sw_dispatch.?.flush_batch(@ptrCast(&ctx), @ptrCast(&ps));
        const elapsed_ns = monotonicNs() - start_ns;
        if (elapsed_ns < min_ns) min_ns = elapsed_ns;
    }
    const elapsed_ms: f64 = float64(min_ns) / 1_000_000.0;

    // 6. Report.
    const total_pixels: u64 = WIDTH * HEIGHT;
    const pixels_per_sec: f64 = float64(total_pixels) /
        (float64(min_ns) / 1_000_000_000.0);
    const mpx_per_sec: f64 = pixels_per_sec / 1_000_000.0;
    std.debug.print(
        "render time:  {d:.2} ms  (min over {d} runs)\n" ++
            "pixels:       {d:.0}\n" ++
            "throughput:   {d:.2} Mpx/s  (~{d:.1} fps at this size)\n",
        .{
            elapsed_ms,            ITERS,
            float64(total_pixels), mpx_per_sec,
            1000.0 / elapsed_ms,
        },
    );

    // 7. Save the result.
    const out_path: []const u8 = "mandelbrot.png";
    try writePng(gpa, io, out_path, ctx.colorBufferBytes(), WIDTH, HEIGHT);
    std.debug.print("saved:        {s}\n", .{out_path});
}
